on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: phopencti.azurecr.io
        username: ${{ secrets.acr_phopencti_username }}
        password: ${{ secrets.acr_phopencti_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/opencti-platform" -f  "opencti-platform/Dockerfile" -t phopencti.azurecr.io/opencti:${{ github.sha }}
        docker push phopencti.azurecr.io/opencti:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_opencti_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep openctie1e2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace openctie1e2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: openctie1e2
        container-registry-url: phopencti.azurecr.io
        container-registry-username: ${{ secrets.acr_phopencti_username }}
        container-registry-password: ${{ secrets.acr_phopencti_password }}
        secret-name: openctidockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: openctie1e2
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
          manifests/ingress-1.yml
        images: |
          phopencti.azurecr.io/opencti:${{ github.sha }}
        imagepullsecrets: |
          openctidockerauth