on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n phopencti -g phopencti9dcd-rg --location "Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n phopencti --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n phopencti --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n phopencti --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: phopencti.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/opencti-platform" -f  "opencti-platform/Dockerfile" -t phopencti.azurecr.io/opencti:${{ github.sha }}
        docker push phopencti.azurecr.io/opencti:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_opencti_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep opencti2a7a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace opencti2a7a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: opencti2a7a
        container-registry-url: phopencti.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: openctidockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: opencti2a7a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          phopencti.azurecr.io/opencti:${{ github.sha }}
        imagepullsecrets: |
          openctidockerauth